# 库方法抛出异常

在程序运行过程中，如果JVM检测出一个**不可能执行的操作**，就会出现**运行时错误(runtime error)**。
    - 如果**使用一个越界的下标访问数组**，程序就会产生一个`ArrayIndexOutOfBoundsException`的运行时错误。
    - 如果程序需要输入一个整数的时候用户输入了一个`double`值，会得到一个`InputMismatchException`的运行时错误。

在Java中，运行时错误会作为异常抛出。**异常就是一个从异常类创建的对象**，表示阻止正常进行程序执行的错误或者情况。如果异常没有被处理，那么程序将会非正常终止。**异常是从方法抛出的**，方法的调用者可以捕获以及处理该异常。

```java {.line-numbers highlight=24}
import java.util.Scanner;

public class Quotient {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.print("Enter two integers: ");
        int number1 = input.nextInt();
        int number2 = input.nextInt();

        try {
            // If ArithmeticException occurs catch Exception
            int result = quotient(number1, number2);
            System.out.println(number1 + " / " + number2 + " is " + (result));
        } catch (ArithmeticException ex) {
            System.out.println("Exception: an integer cannot be divided by zero.");
        } finally {
            System.out.println("Execution continues ...");
        }
    }

    public static int quotient(int number1, int number2) {
        // 不加if语句也能捕获异常
        if (number2 == 0) {
            throw new ArithmeticException("Divisor cannot be zero.");
        }

        return number1 / number2;
    }
}
```

```java
package java.lang;

/**
 * Thrown when an exceptional arithmetic condition has occurred. For
 * example, an integer "divide by zero" throws an instance of this class.
 */
public class ArithmeticException extends RuntimeException {
    private static final long serialVersionUID = 2256477558314496007L;

    public ArithmeticException() {
        super();
    }

    public ArithmeticException(String s) {
        super(s);
    }
}
```

异常处理的优点：能使方法抛出一个异常给它的调用者，并由调用者处理该异常。如果没有这个能力，那么被调用的方法就必须自己处理异常或者终止该程序。

被调用的方法通常不知道在出错的情况下该做些什么，这是**库方法**的一般情况。**库方法可以检测出错误**，但是**只有调用者才知道出现错误时需要做些什么**。

异常处理最根本的优势就是**将检测错误（由被调用的方法完成）从处理错误（由调用方法完成）中分离出来**。


```java
import java.util.InputMismatchException;
import java.util.Scanner;

public class InputMismatch {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        try {
            System.out.print("Enter an integer: ");
            // If InputMismatchException occurs catch Exception
            int number = input.nextInt();
            System.out.println("The number entered is " + number);
        } catch (InputMismatchException e) {
            System.out.println("Incorrect input.");
        }
    }
}
```

# 异常类型

异常是对象，而对象都采用类来定义。异常的根类是`java.lang.Throwable`。

<div align=center><img src=Pictures\异常类型.jpg></div>

异常类可以分为三种主要类型：系统错误、异常和运行时异常：

- 系统错误(system error)是由Java虚拟机抛出的，用Error类表示。**Error类描述的是内部系统错误**。这样的错误很少发生。如果发生，除了**通知用户以及尽量稳妥地终止程序**外，几乎什么也不能做。
- 异常(exception)是用Exception类表示的，它描述的是**由程序和外部环境所引起的错误，这些错误能被程序捕获和处理**。
  - 运行时异常(runtime exception)是用RuntimeException类表示的，它描述的是**程序设计错误**，例如，错误的类型转换、访问一个越界数组或数值错误。运行时异常通常是由Java虚拟机抛出的。
    - `NullPointerException`：试图通过一个null引用变量访问一个对象


- 免检异常(unchecked exception)
  - `RuntimeException`、`Error`以及`它们的子类`都是免检异常
- 必检异常(checked exception)：`IOException`
  - 编译器会强制程序员检查并通过`try-catch`块处理，或者在方法头进行声明


# 异常处理

Java的异常处理模型基于三种操作：声明一个异常、抛出一个异常和捕获一个异常：

<div align=center><img src=Pictures\异常处理.jpg></div>

## 声明异常-throws

每个方法都必须显式声明它可能抛出的**必检异常**的类型（不必显式声明Error和RuntimeException等免检异常）：
`public void myMethod() throws IOException, Exception1...`

## 抛出异常-throw

检测到错误的程序可以创建一个合适的异常类型的实例并抛出它，这就称为抛出一个异常：
`throw new IllegalArgumentException("Wrong Argument");`

## 捕获异常

如果在执行try块的过程中没有出现异常，则跳过catch子句。如果try块中的某条语句抛出一个异常，Java就会跳过try块中剩余的语句，然后开始査找处理这个异常的代码的过程。

# finally

无论异常是否产生，finally子句总是会被执行的。

